name: Deploy Api Schwarz App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Add Python to PATH
      run: |
        echo "C:\Users\guilherme.gordiano\AppData\Local\Programs\Python\Python312\Scripts" >> $env:GITHUB_PATH
        echo "C:\Users\guilherme.gordiano\AppData\Local\Programs\Python\Python312" >> $env:GITHUB_PATH

    - name: Print PATH environment variable
      run: echo $env:PATH

    - name: Verify Python Version
      run: python --version

    - name: Install dependencies
      run: |
        python -m venv venv
        venv\Scripts\Activate
        pip install -r requirements.txt

    - name: Copy dotenv file
      run: |
        copy .env.example .env
        echo STRING_CONNECTION=${{ secrets.STRING_CONNECTION }} >> .env
        echo SMTP_EMAIL_REMETENTE=${{ secrets.SMTP_EMAIL_REMETENTE }} >> .env
        echo SMTP_SENHA_REMETENTE=${{ secrets.SMTP_SENHA_REMETENTE }} >> .env
