name: Deploy Api Schwarz App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:     
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m venv venv
        venv\Scripts\Activate
        pip install -r requirements.txt
        
    - name: Copy dotenv file
      run: |
        copy .env.example .env
        echo STRING_CONNECTION=${{ secrets.STRING_CONNECTION }} >> .env
        echo SMTP_EMAIL_REMETENTE=${{ secrets.SMTP_EMAIL_REMETENTE }} >> .env
        echo SMTP_SENHA_REMETENTE=${{ secrets.SMTP_SENHA_REMETENTE }} >> .env
    - name: Run Flask app with Waitress
      run: |
        venv\Scripts\activate
        waitress-serve --port=8080 app:app
