name: Deploy Api Schwarz App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:     
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m venv venv
        venv\Scripts\Activate
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        cat <<EOF > .env
        STRING_CONNECTION=${{ secrets.STRING_CONNECTION }}
        SMTP_EMAIL_REMETENTE=${{ secrets.SMTP_EMAIL_REMETENTE }}
        SMTP_SENHA_REMETENTE=${{ secrets.SMTP_SENHA_REMETENTE }}
        EOF

    - name: Run Flask app with Waitress
      run: |
        venv\Scripts\activate
        waitress-serve --port=8080 app:app
